In [6]:
import os
import numpy

distance_file = os.path.join ('data', 'distance_data_headers.csv')
print(distance_file)

data\distance_data_headers.csv


In [7]:
distances = numpy.genfromtxt(fname=distance_file, delimiter=',', dtype = 'unicode')
print(distances)

[['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']
 ['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


In [8]:
headers = distances[0]
print(headers)

data = distances[1:]
print(data)

['Frame' 'THR4_ATP' 'THR4_ASP' 'TYR6_ATP' 'TYR6_ASP']
[['1' '8.9542' '5.8024' '11.5478' '9.9557']
 ['2' '8.6181' '6.0942' '13.9594' '11.6945']
 ['3' '9.0066' '6.0637' '13.0924' '11.3043']
 ...
 ['9998' '8.6625' '7.7306' '9.5469' '10.3063']
 ['9999' '9.2456' '7.8886' '9.8151' '10.7564']
 ['10000' '8.8135' '7.917' '9.9517' '10.7848']]


In [9]:
data = data.astype(float)
print(data)

[[1.00000e+00 8.95420e+00 5.80240e+00 1.15478e+01 9.95570e+00]
 [2.00000e+00 8.61810e+00 6.09420e+00 1.39594e+01 1.16945e+01]
 [3.00000e+00 9.00660e+00 6.06370e+00 1.30924e+01 1.13043e+01]
 ...
 [9.99800e+03 8.66250e+00 7.73060e+00 9.54690e+00 1.03063e+01]
 [9.99900e+03 9.24560e+00 7.88860e+00 9.81510e+00 1.07564e+01]
 [1.00000e+04 8.81350e+00 7.91700e+00 9.95170e+00 1.07848e+01]]


In [10]:
array_name[row,column]

NameError: name 'array_name' is not defined

In [ ]:
print(data[0,1])
print(data[1,0])

8.9542
2.0


In [ ]:
small_data = data[0:10, 0:3]
print(small_data)

[[ 1.      8.9542  5.8024]
 [ 2.      8.6181  6.0942]
 [ 3.      9.0066  6.0637]
 [ 4.      9.2002  6.0227]
 [ 5.      9.1294  5.9365]
 [ 6.      9.0462  6.2553]
 [ 7.      8.8657  5.9186]
 [ 8.      9.3256  6.2351]
 [ 9.      9.4184  6.1993]
 [10.      9.06    6.0478]]


In [ ]:
print(small_data[5,:])

[6.     9.0462 6.2553]


In [ ]:
print(small_data[:,1:])

[[8.9542 5.8024]
 [8.6181 6.0942]
 [9.0066 6.0637]
 [9.2002 6.0227]
 [9.1294 5.9365]
 [9.0462 6.2553]
 [8.8657 5.9186]
 [9.3256 6.2351]
 [9.4184 6.1993]
 [9.06   6.0478]]


find average of a column

In [ ]:
thr4_atp = data[:,1]
avg_thr4_atp = numpy.mean(thr4_atp)
print(avg_thr4_atp)

10.876950930000001


In [ ]:
num_columns = len(data[1,:])
print(num_columns)

5


In [ ]:
for i in range (1, num_columns):
    columns = data[1,:]
    avg_columns = numpy.mean(columns)
    print(F'{headers[i]} : {avg_columns}')

THR4_ATP : 8.47324
THR4_ASP : 8.47324
TYR6_ATP : 8.47324
TYR6_ASP : 8.47324


Write a code to read in the information from the xyz file and determine the bond lengths between all the atoms.

uses the numpy.genfromtxt() function to read in the data

In [ ]:
import numpy
import os

file_location = os.path.join('data', 'water.xyz')
xyz_file = numpy.genfromtxt(fname=file_location, skip_header=2, dtype ='unicode')
symbols = xyz_file[:,0]
print(symbols)
coordinates = (xyz_file[:,1:])
#print(coordinates)
coordinates = coordinates.astype(float)
print(coordinates)
num_atoms = len(symbols)
print(num_atoms)

for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        x_distance = coordinates[num1,0] - coordinates[num2,0]
        y_distance = coordinates[num1,1] - coordinates[num2,1]
        z_distance = coordinates[num1,2] - coordinates[num2,2]
        distance = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
        bond_length_12 = numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
        print(F'{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}')  

['O' 'H1' 'H2']
[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]
3
O to O : 0.000
O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H1 to H1 : 0.000
H1 to H2 : 1.527
H2 to O : 0.969
H2 to H1 : 1.527
H2 to H2 : 0.000


solution that uses read lines

In [ ]:
import numpy 
import os
file_location = os.path.join('data', 'water.xyz')
xyzfile = open(file_location,"r")
data = xyzfile.readlines()
num_atoms = int(data[0])
data = data[2:]

symbols = []
coordinates = []

for atom in data:
    atom_data = atom.split()
    symbol = atom_data[0]
    symbols.append(symbol)
    x, y, z = atom_data[1], atom_data[2], atom_data[3]
    coordinates.append([float(x), float(y), float(z)])

for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        atom1 = coordinates[num1]
        atom2 = coordinates[num2]
        x_distance = atom1[0] - atom2[0]
        y_distance = atom1[1] - atom2[1]
        z_distance = atom1[2] - atom2[2]
        bond_length_12 = numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
        print(F'{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}')


O to O : 0.000
O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H1 to H1 : 0.000
H1 to H2 : 1.527
H2 to O : 0.969
H2 to H1 : 1.527
H2 to H2 : 0.000


Modified code to only print the atoms that are actually bonded to each other. 
Add if statement before print

In [ ]:
import numpy 
import os
file_location = os.path.join('data', 'water.xyz')
xyzfile = open(file_location,"r")
data = xyzfile.readlines()
num_atoms = int(data[0])
data = data[2:]

symbols = []
coordinates = []

for atom in data:
    atom_data = atom.split()
    symbol = atom_data[0]
    symbols.append(symbol)
    x, y, z = atom_data[1], atom_data[2], atom_data[3]
    coordinates.append([float(x), float(y), float(z)])
    
    
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        atom1 = coordinates[num1]
        atom2 = coordinates[num2]
        x_distance = atom1[0] - atom2[0]
        y_distance = atom1[1] - atom2[1]
        z_distance = atom1[2] - atom2[2]
        bond_length_12 = numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
        if bond_length_12 > 0 and bond_length_12 <= 1.5:
            print(F'{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}')

O to H1 : 0.969
O to H2 : 0.969
H1 to O : 0.969
H2 to O : 0.969


Some of these are actually the same bond length; for example, O to H1 and H1 to O refer to the same bond length. Remove the duplicates from your list.

In [ ]:
import numpy
import os

file_location = os.path.join('data', 'water.xyz')
xyz_file = numpy.genfromtxt(fname=file_location, skip_header=2, dtype='unicode')
symbols = xyz_file[:,0]
coordinates = (xyz_file[:,1:])
coordinates = coordinates.astype(float)
num_atoms = len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        if num1<num2:
            x_distance = coordinates[num1,0] - coordinates[num2,0]
            y_distance = coordinates[num1,1] - coordinates[num2,1]
            z_distance = coordinates[num1,2] - coordinates[num2,2]
            bond_length_12 = numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
            if bond_length_12 > 0 and bond_length_12 <= 1.5:
                print(F'{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}')

O to H1 : 0.969
O to H2 : 0.969
