In [1]:
import numpy
import os

file_location = os.path.join('data', 'water.xyz')
xyz_file = numpy.genfromtxt(fname=file_location, skip_header=2, dtype='unicode')
symbols = xyz_file[:, 0]
coordinates = xyz_file[:, 1:]
coordinates = coordinates.astype(float)
num_atoms = len(symbols)
for num1 in range(0, num_atoms):
    for num2 in range(0, num_atoms):
        if num1 < num2:
            x_distance = coordinates[num1, 0] - coordinates[num2, 0]
            y_distance = coordinates[num1, 1] - coordinates[num2, 1]
            z_distance = coordinates[num1, 2] - coordinates[num2, 2]
            bond_length_12 = numpy.sqrt(x_distance ** 2 + y_distance ** 2 + z_distance ** 2)
            if bond_length_12 > 0 and bond_length_12 <= 1.5:
                print(F'{symbols[num1]} to {symbols[num2]} : {bond_length_12:.3f}')

O to H1 : 0.969
O to H2 : 0.969


In [2]:
import os
import numpy

file_location = os.path.join('data', 'water.xyz')
xyz_file = numpy.genfromtxt(fname=file_location, skip_header=2, dtype='unicode')
symbols = xyz_file[:,0]
print(symbols)
coordinates = xyz_file[:,1:]
coordinates = coordinates.astype(float)
num_atoms= len(symbols)

def calculate_distance(atom1_coord, atom2_coord):
    x_distance = atom1_coord[0] - atom2_coord[0]
    y_distance = atom1_coord[1] - atom2_coord[1]
    z_distance = atom1_coord[2] - atom2_coord[2]
    bond_length12 = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2)
    return bond_length12

def bond_check(atom_distance):
    if atom_distance > 0 and atom_distance <= 1.5:
        return true
    else:
        return false


['O' 'H1' 'H2']


In [3]:
help(numpy.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must retu

In [4]:
help(calculate_distance)

Help on function calculate_distance in module __main__:

calculate_distance(atom1_coord, atom2_coord)



In [5]:
def bond_check(atom_distance):
    if atom_distance > 0 and atom_distance <= 1.5:
        return True
    else:
        return False

Modify the bond_check function to take a minimum length and a maximum length as user input.

In [6]:
def bond_check(atom_distance, minimum_length, maximum_length):
   if atom_distance > minimum_length and atom_distance <= maximum_length:
       return True
   else:
       return False

In [7]:
def bond_check(atom_distance, minimum_length=0, maximum_length=1.5):
    """
    check if a distance is bond based on a minimum and maximum bond length.
    """
    if atom_distance > minimum_length and atom_distance <= maximum_length:
        return True
    else:
        False
    


In [8]:
print(bond_check(1.5))
print(bond_check(1.6))

True
None


In [9]:
print(bond_check(1.6, maximum_length=1.6))

True


In [10]:
num_atoms = len(symbols)
for num1 in range(0 , num_atoms):
    for num2 in range(0, num_atoms):
        if num1 < num2:
            bond_length12 = calculate_distance(coordinates[num1], coordinates[num2])
            if bond_check(bond_length12) is True:
                print(F'{symbols[num1]} to {symbols[num2]}: {bond_length12:.3f}')
            
        

O to H1: 0.969
O to H2: 0.969


 Write a function called open_xyz which takes an xyz file as a parameter and returns the symbols and coordinates.

In [11]:
def open_xyz(file_name):
    xyz_file = numpy.genfromtxt(fname=file_name, skip_header=2, dtype='unicode')
   
    symbols = xyz_file[:,0]
    coord = xyz_file[:,1:]
    coord = coord.astype(float)
    return symbols, coord

Define all functions

In [12]:
import os
import numpy

def distance_coordinates(atom1coord, atom2coord):
    
    #calculate distance between 2D points
    
    x_distance = atom1coord[0] - atom2coord[0]
    y_distance = atom1coord[1] - atom2coord[1]
    z_distance = atom1coord[2] - atom2coord[2]
    bond_length = numpy.sqrt(x_distance**2 + y_distance**2 + z_distance**2) 
    return bond_length

In [13]:
def bond_check(atom_distance, minimum_distance=0, maximum_distance=1.5):
    
    if atom_distance > minimum_distance and atom_distance <= maximum_distance:
        return True
    else:
        return False

In [14]:
def print_bonds(atom_symbols, atom_coordinates):
    """
    Prints atom symbols and bond length for a set of atoms.
    """
    num_atoms = len(atom_symbols)
    for num1 in range(0, num_atoms):
        for num2 in range(0, num_atoms):
            if num1 < num2:
                bond_length_12 = calculate_distance(atom_coordinates[num1], atom_coordinates[num2])
                if bond_check(bond_length_12) is True:
                    print(F'{atom_symbols[num1]} to {atom_symbols[num2]} : {bond_length_12:.3f}')

In [15]:
water_file_location = os.path.join('data', 'water.xyz')
water_symbols, water_coords = open_xyz(water_file_location)

benzene_file_location = os.path.join('data', 'benzene.xyz')
benzene_symbols, benzene_coords = open_xyz(benzene_file_location)

print(F'printing bonds for water')
print_bonds(water_symbols, water_coords)

print(F'printing bonds for benzene')
print_bonds(benzene_symbols, benzene_coords)



printing bonds for water
O to H1 : 0.969
O to H2 : 0.969
printing bonds for benzene
C to H : 1.088
C to C : 1.403
C to C : 1.403
C to H : 1.088
C to C : 1.403
C to H : 1.088
C to C : 1.403
C to H : 1.088
C to C : 1.403
C to H : 1.088
C to C : 1.403
C to H : 1.088


we used glob to process multiple files. How could you use glob to print bonds for all the xyz files?

In [16]:
import glob

xyz_files = glob.glob("data/*.xyz")

for xyz_file in xyz_files:
    atom_symbols, atom_coords = open_xyz(xyz_file)
    print("printing bonds for", xyz_file)
    print_bonds(atom_symbols, atom_coords)


printing bonds for data\benzene.xyz
C to H : 1.088
C to C : 1.403
C to C : 1.403
C to H : 1.088
C to C : 1.403
C to H : 1.088
C to C : 1.403
C to H : 1.088
C to C : 1.403
C to H : 1.088
C to C : 1.403
C to H : 1.088
printing bonds for data\buckminsterfullerene.xyz
C to C : 1.453
C to C : 1.453
C to C : 1.395
C to C : 1.453
C to C : 1.395
C to C : 1.453
C to C : 1.395
C to C : 1.453
C to C : 1.395
C to C : 1.395
C to C : 1.453
C to C : 1.453
C to C : 1.395
C to C : 1.453
C to C : 1.453
C to C : 1.453
C to C : 1.453
C to C : 1.395
C to C : 1.453
C to C : 1.453
C to C : 1.453
C to C : 1.453
C to C : 1.395
C to C : 1.453
C to C : 1.453
C to C : 1.453
C to C : 1.453
C to C : 1.453
C to C : 1.395
C to C : 1.453
C to C : 1.395
C to C : 1.395
C to C : 1.453
C to C : 1.453
C to C : 1.395
C to C : 1.453
C to C : 1.453
C to C : 1.395
C to C : 1.453
C to C : 1.453
C to C : 1.395
C to C : 1.453
C to C : 1.453
C to C : 1.395
C to C : 1.453
C to C : 1.453
C to C : 1.395
C to C : 1.453
C to C : 1.453


# Matrix Multiplication (3x1 and 1x3)

A **3×1** matrix (column vector) multiplied by a **1×3** matrix (row vector) gives a **3×3** matrix (outer product).

A **1×3** matrix (row vector) multiplied by a **3×1** matrix (column vector) gives a **1×1** scalar (dot product).

In [17]:
import numpy as np

# 3x1 column vector
A = np.array([[1],
              [2],
              [3]])
print("A (3x1):")
print(A)
print("Shape:", A.shape)

# 1x3 row vector
B = np.array([[4, 5, 6]])
print("\nB (1x3):")
print(B)
print("Shape:", B.shape)

# 3x1 @ 1x3 = 3x3 (outer product)
result_3x3 = A @ B
print("\nA @ B (3x1 × 1x3 = 3x3):")
print(result_3x3)
print("Shape:", result_3x3.shape)

# 1x3 @ 3x1 = 1x1 (dot product / scalar)
result_1x1 = B @ A
print("\nB @ A (1x3 × 3x1 = 1x1):")
print(result_1x1)
print("Shape:", result_1x1.shape)

A (3x1):
[[1]
 [2]
 [3]]
Shape: (3, 1)

B (1x3):
[[4 5 6]]
Shape: (1, 3)

A @ B (3x1 × 1x3 = 3x3):
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Shape: (3, 3)

B @ A (1x3 × 3x1 = 1x1):
[[32]]
Shape: (1, 1)
